package cn.local.manga;

import static cn.local.manga.BatchMangaTranslationReview.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.nio.file.*;
import java.util.*;
import java.util.List;
import javax.imageio.ImageIO;
import org.json.*;

/** Isolated visual hypothesis only: existing live return, original production guard, expanded ROI paste. */
public final class FullRoiPasteCandidateReview {
    static int[][] currentGlyphProtections(JSONObject page,String id,int cropLeft,int cropTop,int w,int h,JSONArray sources){
        List<int[]> protections=new ArrayList<>();for(Object raw:page.getJSONArray("regions")){JSONObject other=(JSONObject)raw;if(other.getString("id").equals(id)||!other.optBoolean("layoutApplied"))continue;JSONArray cells=other.optJSONArray("cells");int left=0,top=0;if(cells!=null){String space=other.optString("cellsCoordinateSpace");JSONArray roi=space.equals("renderRoi")?other.getJSONArray("renderRoi"):other.getJSONObject("cleanupInput").getJSONArray("sourceCrop");left=roi.getInt(0);top=roi.getInt(1);}else if(other.getString("status").equals("failed_red")){NearbyTextLayout.Plan p=NearbyTextLayout.plan(page.getInt("width"),page.getInt("height"),ints(other.getJSONArray("box")),Collections.emptyList(),Collections.emptyList(),other.getString("zh"),null);cells=new JSONArray();for(int i=0;i<p.points.length;i++)cells.put(new JSONArray(new float[]{p.cellLeft(i),p.cellTop(i),p.cellLeft(i)+p.step,p.cellTop(i)+p.step}));}if(cells==null)continue;boolean used=false;for(Object cellRaw:cells){JSONArray cell=(JSONArray)cellRaw;int l=Math.max(0,(int)Math.floor(cell.getDouble(0))+left-cropLeft),t=Math.max(0,(int)Math.floor(cell.getDouble(1))+top-cropTop),r=Math.min(w,(int)Math.ceil(cell.getDouble(2))+left-cropLeft),b=Math.min(h,(int)Math.ceil(cell.getDouble(3))+top-cropTop);if(l<r&&t<b){protections.add(new int[]{l,t,r,b});used=true;}}if(used)sources.put(other.getString("id"));}return protections.toArray(new int[0][]);
    }
    static void review(Path batch,Path output,String id,Path project)throws Exception{
        JSONObject page=null,row=null;for(Object p:json(batch.resolve("all_pages_results.json")).getJSONArray("pages"))for(Object r:((JSONObject)p).getJSONArray("regions"))if(((JSONObject)r).getString("id").equals(id)){page=(JSONObject)p;row=(JSONObject)r;}if(row==null||!row.optBoolean("apiSuccess")||!row.optBoolean("compositeApplied"))throw new Exception("Only a recorded production-accepted result may enter this diagnostic: "+id);
        JSONObject input=row.getJSONObject("cleanupInput"),request=json(batch.resolve("requests").resolve(id).resolve("request_result.json"));Path returned=resolved(batch,request.getString("returnedPath")),inputFile=resolved(batch,input.getString("inputPng")),baseFile=resolved(batch,page.getString("translatedFile"));if(!hash(returned).equals(request.getString("outputSha256"))||!hash(inputFile).equals(request.getString("inputSha256"))||!request.optBoolean("success"))throw new Exception("Recorded successful request image identity mismatch");for(String key:new String[]{"targetBoxes","protectedBoxes"})if(!input.getJSONArray(key).toString().equals(request.getJSONArray(key).toString()))throw new Exception("Request geometry mismatch");
        BufferedImage original=ImageIO.read(Paths.get(input.getString("sourcePage")).toFile()),base=ImageIO.read(baseFile.toFile()),decoded=ImageIO.read(returned.toFile());int w=input.getInt("width"),h=input.getInt("height"),pw=original.getWidth(),ph=original.getHeight();int[] c=ints(input.getJSONArray("sourceCrop"));if(base.getWidth()!=pw||base.getHeight()!=ph||c[2]-c[0]!=w||c[3]-c[1]!=h)throw new Exception("Source/base/ROI dimensions mismatch");ImageCleanup.validateReturnedSize(decoded.getWidth(),decoded.getHeight(),w,h);
        BufferedImage resized=new BufferedImage(w,h,BufferedImage.TYPE_INT_ARGB);Graphics2D resize=resized.createGraphics();resize.setComposite(AlphaComposite.Src);resize.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BILINEAR);resize.drawImage(decoded,0,0,w,h,null);resize.dispose();int[] before=original.getRGB(c[0],c[1],w,h,null,0,w),after=resized.getRGB(0,0,w,h,null,0,w),basePixels=base.getRGB(0,0,pw,ph,null,0,pw),finalPixels=basePixels.clone();int[][] protections=boxes(input.getJSONArray("protectedBoxes"));boolean[] oldEditable=RepairPixels.editable(w,h,boxes(input.getJSONArray("targetBoxes")),protections);
        // This is the original production validation, before expanding a single paste pixel.
        RepairPixels.composite(before,after,w,h,oldEditable);JSONArray protectedSources=new JSONArray();int[][] glyphProtections=currentGlyphProtections(page,id,c[0],c[1],w,h,protectedSources);List<int[]> allProtections=new ArrayList<>(Arrays.asList(protections));allProtections.addAll(Arrays.asList(glyphProtections));protections=allProtections.toArray(new int[0][]);boolean[] expanded=RepairPixels.editable(w,h,new int[][]{{0,0,w,h}},protections);JSONObject diagnostic=new JSONObject().put("id",id);diagnostics(output,diagnostic,before,after,w,h,expanded);Path diagnosticFiles=output.resolve("requests").resolve(id).resolve("合成审查");BufferedImage staged=ImageIO.read(diagnosticFiles.resolve("仅目标2px羽化_诊断候选.png").toFile());NearbyTextLayout.Plan plan=NearbyTextLayout.forCrop(pw,ph,ints(row.getJSONArray("box")),c[0],c[1],row.getBoolean("vertical"),row.getString("zh"));
        for(int i=0;i<plan.points.length;i++){float x=plan.cellLeft(i),y=plan.cellTop(i);for(int[] b:protections)if(x<b[2]+2&&x+plan.step>b[0]-2&&y<b[3]+2&&y+plan.step>b[1]-2)throw new Exception("Original Chinese layout overlaps protected text");}Graphics2D text=staged.createGraphics();drawInPlace(text,plan,Color.BLACK);text.dispose();int[] stagedPixels=staged.getRGB(0,0,w,h,null,0,w);int committed=0;for(int y=0;y<h;y++)for(int x=0;x<w;x++)if(expanded[y*w+x]){finalPixels[(c[1]+y)*pw+c[0]+x]=stagedPixels[y*w+x];committed++;}
        int outside=0,outsideChanged=0,protectedCount=0,protectedChanged=0;for(int y=0;y<ph;y++)for(int x=0;x<pw;x++)if(x<c[0]||x>=c[2]||y<c[1]||y>=c[3]){outside++;if(basePixels[y*pw+x]!=finalPixels[y*pw+x])outsideChanged++;}for(int y=0;y<h;y++)for(int x=0;x<w;x++)if(!expanded[y*w+x]){protectedCount++;int p=(c[1]+y)*pw+c[0]+x;if(basePixels[p]!=finalPixels[p])protectedChanged++;}if(outsideChanged!=0||protectedChanged!=0)throw new Exception("Expanded candidate escaped ROI or foreign protection");
        Path dir=output.resolve(id);Files.createDirectories(dir);BufferedImage originalRoi=image(before,w,h),currentRoi=image(base.getRGB(c[0],c[1],w,h,null,0,w),w,h),candidateRoi=image(stagedPixels,w,h),candidatePage=image(finalPixels,pw,ph);for(int y=0;y<h;y++)for(int x=0;x<w;x++)candidateRoi.setRGB(x,y,finalPixels[(c[1]+y)*pw+c[0]+x]);
        GroupedBackgroundReview.writeImage(originalRoi,dir.resolve("原图ROI.png"));GroupedBackgroundReview.writeImage(currentRoi,dir.resolve("当前正式回填ROI.png"));GroupedBackgroundReview.writeImage(candidateRoi,dir.resolve("整ROI候选回填.png"));GroupedBackgroundReview.writeImage(candidatePage,dir.resolve("整页候选_不改正式输出.png"));GroupedBackgroundReview.compareImages(dir.resolve("原图_当前_整ROI候选.png"),originalRoi,currentRoi,candidateRoi);
        int[] context={Math.max(0,c[0]-80),Math.max(0,c[1]-80),Math.min(pw,c[2]+80),Math.min(ph,c[3]+80)};GroupedBackgroundReview.compareImages(dir.resolve("上下文_原图_当前_整ROI候选.png"),GroupedBackgroundReview.crop(original,context),GroupedBackgroundReview.crop(base,context),GroupedBackgroundReview.crop(candidatePage,context));
        JSONObject report=new JSONObject().put("id",id).put("diagnosticOnly",true).put("productionOriginalTargetGuardAccepted",true).put("productionImplementationChanged",false).put("formalBatchOutputChanged",false).put("newApiRequests",0).put("originalTargetBoxes",input.getJSONArray("targetBoxes")).put("diagnosticPasteBoxes",new JSONArray(new int[][]{{0,0,w,h}})).put("originalProtectedBoxes",input.getJSONArray("protectedBoxes")).put("protectedBoxes",new JSONArray(protections)).put("extraCurrentGlyphProtectionBoxes",new JSONArray(glyphProtections)).put("extraProtectedSourceIds",protectedSources).put("sourceCrop",input.getJSONArray("sourceCrop")).put("sourcePage",input.getString("sourcePage")).put("baseTranslatedPage",baseFile.toString()).put("baseTranslatedPageSha256",hash(baseFile)).put("requestResultSha256",hash(batch.resolve("requests").resolve(id).resolve("request_result.json"))).put("returnedSha256",hash(returned)).put("inputSha256",hash(inputFile)).put("font",plan.font).put("glyphCount",plan.points.length).put("zh",row.getString("zh")).put("expandedCommittedPixels",committed).put("outsideRoiPixels",outside).put("outsideRoiChangedPixels",outsideChanged).put("foreignProtectedPixels",protectedCount).put("foreignProtectedChangedPixels",protectedChanged).put("candidateSha256",hash(dir.resolve("整ROI候选回填.png"))).put("contextBox",new JSONArray(context)).put("visualStatus","pending_independent_review").put("candidateMethod","Run production RepairPixels.composite on original target mask as admission guard, then reuse model pixels inside entire original ROI with foreign+2 and current translated glyph-cell+2 protection and original-first/half-second/full-third-pixel feather; Chinese plan unchanged.").put("productionSourceSha256",hashes(project));save(dir.resolve("结果.json"),report);System.out.println("FULL ROI CANDIDATE "+id+" outside="+outsideChanged+" protected="+protectedChanged);
    }
    public static void main(String[] args)throws Exception{Path batch=Paths.get(args[0]),output=Paths.get(args[1]),project=Paths.get(args[2]);Files.createDirectories(output);for(int i=3;i<args.length;i++)review(batch,output,args[i],project);}
}
