package cn.local.manga;

import static cn.local.manga.BatchMangaTranslationReview.*;
import java.awt.*;
import java.awt.geom.*;
import java.awt.image.BufferedImage;
import java.nio.file.*;
import java.util.*;
import java.util.List;
import javax.imageio.ImageIO;
import org.json.*;

/** Multi-target background-lettering review. Uses real recorded responses, no network and no production edits. */
public final class GroupedBackgroundReview {
    static JSONObject cloneJson(JSONObject value){return new JSONObject(value.toString());}
    static Map<String,JSONObject> indexed(JSONArray items){Map<String,JSONObject> result=new LinkedHashMap<>();for(Object raw:items){JSONObject v=(JSONObject)raw;String id=v.getString("id");if(result.put(id,v)!=null)throw new IllegalArgumentException("Duplicate id "+id);}return result;}
    static boolean validTranslation(JSONObject text){return text!=null&&!text.optBoolean("skip")&&!text.optString("zh").isBlank();}
    static JSONObject frozenTranslations(Path root,JSONObject manifest)throws Exception{
        Path path=resolved(root,manifest.getString("textTranslationsFile"));if(!hash(path).equals(manifest.getString("textTranslationsSha256")))throw new Exception("Frozen translation snapshot SHA mismatch");JSONObject translation=json(path);Map<String,JSONObject> texts=indexed(translation.getJSONArray("translations"));
        for(Object raw:manifest.getJSONArray("regions"))for(Object memberRaw:((JSONObject)raw).getJSONArray("members")){JSONObject member=(JSONObject)memberRaw,text=texts.get(member.getString("id"));if(!validTranslation(text))throw new Exception("Frozen active member lacks a real translation: "+member.getString("id"));for(String field:new String[]{"zh","sourceText","translationRecord"})if(!member.getString(field).equals(text.getString(field)))throw new Exception("Frozen member translation identity mismatch: "+member.getString("id")+" "+field);}
        return translation;
    }
    static boolean sameBox(int[] a,int[] b){return Arrays.equals(a,b);}
    static BufferedImage crop(BufferedImage image,int[] b){return BatchMangaTranslationReview.image(image.getRGB(b[0],b[1],b[2]-b[0],b[3]-b[1],null,0,b[2]-b[0]),b[2]-b[0],b[3]-b[1]);}
    static void writeImage(BufferedImage image,Path p)throws Exception{Files.createDirectories(p.getParent());ImageIO.write(image,"png",p.toFile());}
    static int grayDelta(int a,int b){return (Math.abs((a>>16&255)-(b>>16&255))+Math.abs((a>>8&255)-(b>>8&255))+Math.abs((a&255)-(b&255)))/3;}
    static void checkMemberTargets(JSONObject active,Map<String,JSONObject> translations)throws Exception{
        JSONArray targets=active.getJSONArray("targetBoxes"),members=active.getJSONArray("members");if(targets.length()!=members.length()||targets.length()==0)throw new Exception("Active members and targets must match one-to-one");int[] sourceCrop=ints(active.getJSONArray("sourceCrop"));
        for(int i=0;i<members.length();i++){JSONObject member=members.getJSONObject(i);if(!validTranslation(translations.get(member.getString("id"))))throw new Exception("Active target has no real non-skip translation: "+member.getString("id"));int[] absolute=ints(member.getJSONArray("absoluteBox")),target=ints(targets.getJSONArray(i)),local=ints(member.getJSONArray("targetBox"));if(!sameBox(target,local)||target[0]+sourceCrop[0]!=absolute[0]||target[1]+sourceCrop[1]!=absolute[1]||target[2]+sourceCrop[0]!=absolute[2]||target[3]+sourceCrop[1]!=absolute[3])throw new Exception("Active target coordinates do not match member "+member.getString("id"));}
    }
    static void excludedMembersProtected(JSONObject planned,JSONObject active)throws Exception{
        Set<String> keep=indexed(active.getJSONArray("members")).keySet();if(!indexed(planned.getJSONArray("members")).keySet().containsAll(keep))throw new Exception("Active group contains a member absent from its frozen plan");for(String field:new String[]{"sourceCrop","sourceSize"})if(!planned.getJSONArray(field).toString().equals(active.getJSONArray(field).toString()))throw new Exception("Active group source geometry differs from planned group");int[][] protections=boxes(active.getJSONArray("protectedBoxes"));int[] sourceCrop=ints(active.getJSONArray("sourceCrop"));
        for(Object raw:planned.getJSONArray("members")){JSONObject member=(JSONObject)raw;if(keep.contains(member.getString("id")))continue;int[] b=ints(member.getJSONArray("absoluteBox"));int l=Math.max(0,b[0]-sourceCrop[0]),t=Math.max(0,b[1]-sourceCrop[1]),r=Math.min(active.getInt("width"),b[2]-sourceCrop[0]),bottom=Math.min(active.getInt("height"),b[3]-sourceCrop[1]);if(l>=r||t>=bottom)continue;boolean covered=false;for(int[] p:protections)if(p[0]<=l&&p[1]<=t&&p[2]>=r&&p[3]>=bottom)covered=true;if(!covered)throw new Exception("Skipped/missing member is not protected: "+member.getString("id"));}
    }
    static JSONObject validateParagraphProtection(JSONObject active)throws Exception{
        if(!active.has("explicitSelfRegionIds"))throw new Exception("Missing explicitSelfRegionIds; geometric containment is not proof of the same lettering");Set<String> self=new HashSet<>();for(Object raw:active.getJSONArray("explicitSelfRegionIds"))self.add(String.valueOf(raw));int[] roi=ints(active.getJSONArray("sourceCrop"));int[][] protections=boxes(active.getJSONArray("protectedBoxes"));JSONArray checked=new JSONArray();Set<String> known=new HashSet<>();Path source=Paths.get(active.getString("sourcePage"));
        for(Object raw:json(source.getParent().resolve("段落检测.json")).getJSONArray("regions")){JSONObject region=(JSONObject)raw;String id=region.getString("id");known.add(id);if(self.contains(id))continue;JSONObject box=region.getJSONObject("box");int x=box.getInt("x"),y=box.getInt("y"),l=Math.max(x,roi[0]),t=Math.max(y,roi[1]),r=Math.min(x+box.getInt("width"),roi[2]),b=Math.min(y+box.getInt("height"),roi[3]);if(l>=r||t>=b)continue;l-=roi[0];t-=roi[1];r-=roi[0];b-=roi[1];boolean covered=false;for(int[] p:protections)if(p[0]<=l&&p[1]<=t&&p[2]>=r&&p[3]>=b)covered=true;if(!covered)throw new Exception("Non-self original paragraph lacks full protection: "+id+" "+new JSONArray(new int[]{l,t,r,b}));checked.put(id);}
        if(!known.containsAll(self))throw new Exception("explicitSelfRegionIds contains an unknown original region");return new JSONObject().put("explicitSelfRegionIds",active.getJSONArray("explicitSelfRegionIds")).put("nonSelfIntersectingParagraphsProtected",checked).put("containmentNotUsedForSelfMatching",true);
    }
    static Map<String,JSONObject> prepareMemberReports(JSONObject group,Map<String,JSONObject> translations,Map<String,JSONObject> activeMembers){
        Map<String,JSONObject> results=new LinkedHashMap<>();for(Object raw:group.getJSONArray("members")){JSONObject member=cloneJson((JSONObject)raw),text=translations.get(member.getString("id"));member.put("groupId",group.getString("id")).put("page",group.getInt("page")).put("apiSubmitted",false).put("apiSuccess",false).put("groupCompositeAccepted",false).put("cleanupApplied",false).put("layoutApplied",false).put("visualStatus","pending");if(text!=null)member.put("translation",text).put("translationStatus",text.optString("status","unknown")).put("zh",text.optString("zh")).put("sourceText",text.optString("sourceText",text.optString("originalText")));
            if(activeMembers.containsKey(member.getString("id")))member.put("status","pending");else if(text!=null&&text.optBoolean("skip"))member.put("status","model_skip").put("visualStatus","preserved_original");else member.put("status",validTranslation(text)?"excluded_from_cleanup":"missing_translation").put("visualStatus","preserved_original");results.put(member.getString("id"),member);
        }return results;
    }
    static void applyGroup(Path root,BufferedImage original,BufferedImage current,JSONObject active,JSONObject report,Map<String,JSONObject> texts,Map<String,JSONObject> memberReports)throws Exception{
        report.put("processingStage","request_response").put("compositeAccepted",false).put("applied",false);JSONObject request=requestMetadata(root,report);for(JSONObject m:memberReports.values())if(indexed(active.getJSONArray("members")).containsKey(m.getString("id")))m.put("apiSubmitted",report.optBoolean("apiSubmitted")).put("apiSuccess",report.optBoolean("apiSuccess"));
        if(request==null)throw new Exception("图像去字请求尚未完成");if(!request.optBoolean("success"))throw new Exception("图像去字未成功："+request.optString("failure",request.optString("status")));report.put("processingStage","request_identity");
        Path input=resolved(root,active.getString("inputPng")),returned=resolved(root,request.getString("returnedPath"));if(!hash(input).equals(active.getString("inputSha256"))||!active.getString("inputSha256").equals(request.getString("inputSha256"))||!hash(returned).equals(request.getString("outputSha256")))throw new Exception("真实请求输入/返回SHA不匹配");
        for(String field:new String[]{"width","height"})if(active.getInt(field)!=request.getInt(field))throw new Exception("请求尺寸不匹配");for(String field:new String[]{"targetBoxes","protectedBoxes"})if(!active.getJSONArray(field).toString().equals(request.getJSONArray(field).toString()))throw new Exception("请求目标或保护框不匹配");
        int w=active.getInt("width"),h=active.getInt("height");int[] sourceCrop=ints(active.getJSONArray("sourceCrop"));if(sourceCrop[2]-sourceCrop[0]!=w||sourceCrop[3]-sourceCrop[1]!=h)throw new Exception("源图裁切尺寸不匹配");int[][] targets=boxes(active.getJSONArray("targetBoxes")),protections=boxes(active.getJSONArray("protectedBoxes"));ImageCleanup.prompt(w,h,targets,protections);report.put("processingStage","returned_size_decode");BufferedImage decoded=ImageIO.read(returned.toFile());if(decoded==null)throw new Exception("模型图像无法解码");ImageCleanup.validateReturnedSize(decoded.getWidth(),decoded.getHeight(),w,h);
        BufferedImage scaled=new BufferedImage(w,h,BufferedImage.TYPE_INT_ARGB);Graphics2D scale=scaled.createGraphics();scale.setComposite(AlphaComposite.Src);scale.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BILINEAR);scale.drawImage(decoded,0,0,w,h,null);scale.dispose();report.put("inputWidth",w).put("inputHeight",h).put("returnedWidth",decoded.getWidth()).put("returnedHeight",decoded.getHeight()).put("returnedPath",relative(root,returned)).put("outputSha256",request.getString("outputSha256"));
        int[] before=original.getRGB(sourceCrop[0],sourceCrop[1],w,h,null,0,w),after=scaled.getRGB(0,0,w,h,null,0,w);boolean[] editable=RepairPixels.editable(w,h,targets,protections);after=normalizeReturned(before,after,w,h,editable,decoded,report);scaled.setRGB(0,0,w,h,after,0,w);diagnostics(root,report,before,after,w,h,editable);report.put("processingStage","production_multi_target_composite");int[] merged=RepairPixels.composite(before,after,w,h,editable);report.put("compositeAccepted",true);int outside=0;for(int p=0;p<merged.length;p++)if(!editable[p]&&merged[p]!=before[p])outside++;if(outside!=0)throw new Exception("组保护区像素被更改");report.put("outsideCompositeChangedPixels",outside);
        Path review=root.resolve("requests").resolve(active.getString("id")).resolve("回填审查");writeImage(image(before,w,h),review.resolve("原图ROI.png"));writeImage(scaled,review.resolve("模型返回_生产缩回.png"));writeImage(image(merged,w,h),review.resolve("生产保护合成_仅去字.png"));BufferedImage staged=image(merged,w,h);JSONArray memberList=active.getJSONArray("members");report.put("processingStage","per_member_layout");
        for(int index=0;index<memberList.length();index++){
            JSONObject member=memberList.getJSONObject(index),m=memberReports.get(member.getString("id"));int[] absolute=ints(member.getJSONArray("absoluteBox")),target=targets[index];String zh=texts.get(member.getString("id")).getString("zh");NearbyTextLayout.Plan plan=NearbyTextLayout.forCrop(original.getWidth(),original.getHeight(),absolute,sourceCrop[0],sourceCrop[1],member.optBoolean("vertical",true),zh);JSONArray cells=new JSONArray();
            List<int[]> layoutProtection=new ArrayList<>(Arrays.asList(protections));for(int j=0;j<targets.length;j++)if(j!=index)layoutProtection.add(targets[j]);protectedFitEvidence(m,plan,layoutProtection.toArray(new int[0][]));
            for(int i=0;i<plan.points.length;i++){float x=plan.cellLeft(i),y=plan.cellTop(i);JSONArray cell=new JSONArray(new float[]{x,y,x+cellStep(plan,i),y+cellStep(plan,i)});cells.put(cell);for(int protectedIndex=0;protectedIndex<protections.length;protectedIndex++){int[] protect=protections[protectedIndex];if(x<protect[2]+2&&x+cellStep(plan,i)>protect[0]-2&&y<protect[3]+2&&y+cellStep(plan,i)>protect[1]-2){JSONObject conflict=new JSONObject().put("member",member.getString("id")).put("glyphIndex",i).put("cell",cell).put("protectedBoxIndex",protectedIndex).put("protectedBox",new JSONArray(protect));report.put("layoutConflict",conflict);throw new Exception("成员字格覆盖保护框："+conflict);}}for(int j=0;j<targets.length;j++)if(j!=index){int[] other=targets[j];if(x<other[2]+2&&x+cellStep(plan,i)>other[0]-2&&y<other[3]+2&&y+cellStep(plan,i)>other[1]-2){JSONObject conflict=new JSONObject().put("member",member.getString("id")).put("otherMember",memberList.getJSONObject(j).getString("id")).put("glyphIndex",i).put("cell",cell).put("otherTarget",new JSONArray(other));report.put("layoutConflict",conflict);throw new Exception("组内两个目标字格冲突："+conflict);}}}
            int editableCount=0,effective=0;for(int y=Math.max(0,target[1]);y<Math.min(h,target[3]);y++)for(int x=Math.max(0,target[0]);x<Math.min(w,target[2]);x++){int p=y*w+x;if(editable[p]){editableCount++;if(grayDelta(before[p],merged[p])>8)effective++;}}
            m.put("groupCompositeAccepted",true).put("targetEditablePixels",editableCount).put("targetEffectiveChangedOverDelta8",effective).put("targetPixelChangeEvidence",effective<Math.min(8,editableCount)?"insufficient_change_requires_visual_review":"pixels_changed_not_proof_of_text_removal").put("font",plan.font).put("glyphCount",plan.points.length).put("cells",cells).put("cellsCoordinateSpace","group_sourceCrop");fontEvidence(m,plan);
            Graphics2D g=staged.createGraphics();g.clipRect(target[0],target[1],target[2]-target[0],target[3]-target[1]);drawInPlace(g,plan,Color.BLACK);g.dispose();
        }
        // Staging and every member layout must succeed before any part of this group reaches the page.
        int[] filled=staged.getRGB(0,0,w,h,null,0,w);int committed=0;for(int y=0;y<h;y++)for(int x=0;x<w;x++)if(editable[y*w+x]&&filled[y*w+x]!=before[y*w+x]){current.setRGB(sourceCrop[0]+x,sourceCrop[1]+y,filled[y*w+x]);committed++;}writeImage(staged,review.resolve("中文回填_组内预览.png"));report.put("processingStage","committed").put("applied",true).put("committedChangedEditablePixels",committed).put("unchangedSourcePixelsNotRepasted",true).put("status",report.optBoolean("apiSubmitted")?"api_live":"api_cached");for(Object raw:memberList){JSONObject m=memberReports.get(((JSONObject)raw).getString("id"));m.put("status",report.getString("status")).put("cleanupApplied",true).put("layoutApplied",true).put("groupCompositeAccepted",true);}
        decoded.flush();scaled.flush();staged.flush();
    }
    static void redFallback(BufferedImage current,JSONObject active,Map<String,JSONObject> texts,Map<String,JSONObject> memberReports)throws Exception{
        int[] crop=ints(active.getJSONArray("sourceCrop"));int[][] protections=boxes(active.getJSONArray("protectedBoxes"));for(Object raw:active.getJSONArray("members")){JSONObject member=(JSONObject)raw,m=memberReports.get(member.getString("id")),text=texts.get(member.getString("id"));if(m==null)continue;if(!validTranslation(text)){m.put("status","missing_translation").put("visualStatus","preserved_original");continue;}int[] b=ints(member.getJSONArray("absoluteBox"));NearbyTextLayout.Plan plan=NearbyTextLayout.forCrop(current.getWidth(),current.getHeight(),b,0,0,member.optBoolean("vertical",true),text.getString("zh"));List<int[]> layoutProtection=new ArrayList<>();for(int[] p:protections)layoutProtection.add(new int[]{crop[0]+p[0],crop[1]+p[1],crop[0]+p[2],crop[1]+p[3]});for(Object otherRaw:active.getJSONArray("members")){JSONObject other=(JSONObject)otherRaw;if(!other.getString("id").equals(member.getString("id")))layoutProtection.add(ints(other.getJSONArray("absoluteBox")));}protectedFitEvidence(m,plan,layoutProtection.toArray(new int[0][]));Graphics2D g=current.createGraphics();Area clip=new Area(new Rectangle(b[0],b[1],b[2]-b[0],b[3]-b[1]));for(int[] p:protections)clip.subtract(new Area(new Rectangle(crop[0]+p[0]-2,crop[1]+p[1]-2,p[2]-p[0]+4,p[3]-p[1]+4)));for(Object otherRaw:active.getJSONArray("members")){JSONObject other=(JSONObject)otherRaw;if(!other.getString("id").equals(member.getString("id"))){int[] o=ints(other.getJSONArray("absoluteBox"));clip.subtract(new Area(new Rectangle(o[0]-2,o[1]-2,o[2]-o[0]+4,o[3]-o[1]+4)));}}g.clip(clip);drawInPlace(g,plan,Color.RED);g.dispose();m.put("status","failed_red").put("cleanupApplied",false).put("layoutApplied",true).put("originalInkPreserved",true).put("visualStatus","cleanup_not_applied");}
    }
    static JSONArray values(Map<String,JSONObject> entries){JSONArray result=new JSONArray();entries.values().forEach(result::put);return result;}
    static JSONObject memberCounts(JSONArray rows){JSONObject c=new JSONObject().put("members",rows.length());for(Object raw:rows){String status=((JSONObject)raw).getString("status");c.put(status,c.optInt(status)+1);}return c;}
    static JSONObject groupCounts(JSONArray rows){JSONObject c=new JSONObject().put("plannedGroups",rows.length()).put("apiSubmittedGroups",0).put("rawApiSuccessGroups",0).put("pixelCompositeRejectedGroups",0).put("layoutProtectionConflictGroups",0).put("appliedGroups",0).put("pendingImageGroups",0).put("externalQueuePendingMergeGroups",0);for(Object raw:rows){JSONObject row=(JSONObject)raw;if(row.optBoolean("apiSubmitted"))c.increment("apiSubmittedGroups");if(row.optBoolean("apiSuccess"))c.increment("rawApiSuccessGroups");if(row.optString("rejectedStage").equals("production_multi_target_composite"))c.increment("pixelCompositeRejectedGroups");if(row.has("layoutConflict"))c.increment("layoutProtectionConflictGroups");if(row.optBoolean("applied"))c.increment("appliedGroups");if(row.optString("status").equals("pending_image"))c.increment("pendingImageGroups");if(row.optBoolean("externalQueuePendingMerge"))c.increment("externalQueuePendingMergeGroups");}return c;}
    static void awaitingImage(JSONObject active,JSONObject report,Map<String,JSONObject> members,boolean externalQueue){
        report.put("status","pending_image").put("processingStage","awaiting_image_result").put("externalQueuePendingMerge",externalQueue).put("pendingReason",externalQueue?"独立图像队列处理中，结果终局后统一合并":"等待图像队列完成，尚非终局失败");for(Object raw:active.getJSONArray("members")){JSONObject m=members.get(((JSONObject)raw).getString("id"));m.put("status","pending_image").put("cleanupApplied",false).put("layoutApplied",false).put("visualStatus","awaiting_image_result").put("externalQueuePendingMerge",externalQueue).put("originalInkPreserved",true);}
    }
    static void writeBoundaryControl(Path root,BufferedImage original,JSONObject member)throws Exception{
        int[] b=ints(member.getJSONArray("absoluteBox"));Path dir=root.resolve("逐处").resolve(member.getString("id"));
        int[] context={Math.max(0,b[0]-12),Math.max(0,b[1]-12),Math.min(original.getWidth(),b[2]+12),Math.min(original.getHeight(),b[3]+12)};BufferedImage boundary=crop(original,context);Graphics2D g=boundary.createGraphics();g.setStroke(new BasicStroke(1));g.setColor(Color.RED);g.drawRect(b[0]-context[0],b[1]-context[1],b[2]-b[0]-1,b[3]-b[1]-1);if(b[2]-b[0]>4&&b[3]-b[1]>4){g.setColor(Color.CYAN);g.drawRect(b[0]-context[0]+2,b[1]-context[1]+2,b[2]-b[0]-5,b[3]-b[1]-5);}g.dispose();writeImage(boundary,dir.resolve("原图_目标边界与2px内缘.png"));boundary.flush();
        member.put("targetBoundaryControlFile",relative(root,dir.resolve("原图_目标边界与2px内缘.png"))).put("boundaryContext",new JSONArray(context)).put("boundaryControlLegend","Red: target extent; cyan: boundary after 2-pixel inset. Visual check required for source strokes cut by these boundaries.");
    }
    static void writeMemberArtifacts(Path root,BufferedImage original,BufferedImage current,JSONObject member)throws Exception{
        int[] b=ints(member.getJSONArray("absoluteBox"));Path dir=root.resolve("逐处").resolve(member.getString("id"));BufferedImage before=crop(original,b),after=crop(current,b);writeImage(before,dir.resolve("原图ROI.png"));writeImage(after,dir.resolve("实际回填ROI.png"));compareImages(dir.resolve("原图_实际回填.png"),before,after);before.flush();after.flush();writeBoundaryControl(root,original,member);
        member.put("originalRoiFile",relative(root,dir.resolve("原图ROI.png"))).put("translatedRoiFile",relative(root,dir.resolve("实际回填ROI.png"))).put("comparisonFile",relative(root,dir.resolve("原图_实际回填.png")));save(dir.resolve("结果.json"),member);
    }
    static JSONObject verifyPageScope(BufferedImage original,BufferedImage current,List<JSONObject> groups,Map<String,JSONObject> active)throws Exception{
        int w=original.getWidth(),h=original.getHeight();boolean[] allowed=new boolean[w*h];for(JSONObject planned:groups){JSONObject group=active.get(planned.getString("id"));if(group==null)continue;int rw=group.getInt("width"),rh=group.getInt("height");int[] crop=ints(group.getJSONArray("sourceCrop"));boolean[] region=RepairPixels.editable(rw,rh,boxes(group.getJSONArray("targetBoxes")),boxes(group.getJSONArray("protectedBoxes")));for(int y=0;y<rh;y++)for(int x=0;x<rw;x++)if(region[y*rw+x])allowed[(crop[1]+y)*w+crop[0]+x]=true;}
        int[] before=original.getRGB(0,0,w,h,null,0,w),after=current.getRGB(0,0,w,h,null,0,w);int exterior=0,changed=0;for(int p=0;p<allowed.length;p++)if(!allowed[p]){exterior++;if(before[p]!=after[p])changed++;}if(changed!=0)throw new Exception("专项整页有目标并集以外像素变化："+changed);return new JSONObject().put("outsideEditableUnionPixels",exterior).put("outsideEditableUnionChangedPixels",changed).put("outsideEditableUnionByteExact",true);
    }
    static void compareImages(Path output,BufferedImage... images)throws Exception{int w=images[0].getWidth(),h=images[0].getHeight();BufferedImage panel=new BufferedImage(w*images.length+8*(images.length-1),h,BufferedImage.TYPE_INT_RGB);Graphics2D g=panel.createGraphics();g.setColor(new Color(220,220,220));g.fillRect(0,0,panel.getWidth(),panel.getHeight());for(int i=0;i<images.length;i++)g.drawImage(images[i],i*(w+8),0,null);g.dispose();writeImage(panel,output);panel.flush();}
    static BufferedImage cleanupReviewPanel(BufferedImage original,Path cleaned,JSONObject report)throws Exception{
        boolean available=report.optBoolean("compositeAccepted")&&Files.isRegularFile(cleaned);BufferedImage panel=available?ImageIO.read(cleaned.toFile()):new BufferedImage(original.getWidth(),original.getHeight(),BufferedImage.TYPE_INT_RGB);if(available&&report.optBoolean("applied")){report.put("cleanedPanelStatus","applied_cleanup_preview");return panel;}
        String note=available?"仅去字候选，未应用":report.optString("status").equals("pending_image")?"等待图像结果":"去字未应用";Graphics2D g=panel.createGraphics();g.setFont(new Font("Microsoft YaHei",Font.PLAIN,Math.max(8,Math.min(16,(panel.getWidth()-8)/note.length()))));FontMetrics fm=g.getFontMetrics();g.setColor(new Color(235,235,235));g.fillRect(0,0,panel.getWidth(),available?fm.getHeight()+6:panel.getHeight());g.setColor(new Color(150,35,35));g.drawString(note,Math.max(2,(panel.getWidth()-fm.stringWidth(note))/2),available?fm.getAscent()+3:Math.max(fm.getAscent(),panel.getHeight()/2));g.dispose();report.put("cleanedPanelStatus",available?"composite_candidate_not_applied":"not_applied_placeholder");return panel;
    }
    static BufferedImage annotate(BufferedImage current,JSONArray rows){BufferedImage marked=image(current.getRGB(0,0,current.getWidth(),current.getHeight(),null,0,current.getWidth()),current.getWidth(),current.getHeight());Graphics2D g=marked.createGraphics();g.setFont(new Font("Microsoft YaHei",Font.BOLD,13));for(Object raw:rows){JSONObject m=(JSONObject)raw;int[] b=ints(m.getJSONArray("absoluteBox"));String status=m.getString("status");g.setColor(status.startsWith("api_")?new Color(155,35,205):status.equals("failed_red")?Color.RED:Color.GRAY);g.setStroke(new BasicStroke(m.optBoolean("apiSubmitted")?3:1));g.drawRect(b[0],b[1],b[2]-b[0],b[3]-b[1]);String label=m.getString("id");FontMetrics fm=g.getFontMetrics();int x=Math.min(b[0],Math.max(0,marked.getWidth()-fm.stringWidth(label))),y=Math.max(fm.getAscent(),b[1]-2);g.drawString(label,x,y);}g.dispose();return marked;}
    static void render(Path root,Path project)throws Exception{
        JSONObject planned=json(root.resolve("group_plan.json")),manifest=json(root.resolve("cleanup_manifest.json")),translation=frozenTranslations(root,manifest);Map<String,JSONObject> activeGroups=indexed(manifest.getJSONArray("regions")),texts=indexed(translation.getJSONArray("translations"));TreeMap<Integer,List<JSONObject>> pages=new TreeMap<>();Set<String> groupedIds=new HashSet<>();for(Object raw:planned.getJSONArray("regions")){JSONObject group=(JSONObject)raw;pages.computeIfAbsent(group.getInt("page"),unused->new ArrayList<>()).add(group);groupedIds.addAll(indexed(group.getJSONArray("members")).keySet());}JSONArray inventory=Files.isRegularFile(root.resolve("background_inventory.json"))?json(root.resolve("background_inventory.json")).getJSONArray("targets"):new JSONArray();
        Set<String> externalQueueIds=new HashSet<>();Path partition=root.resolve("image_queue_002/queue_partition.json");if(Files.isRegularFile(partition))for(Object id:json(partition).getJSONArray("queuedIds"))externalQueueIds.add(String.valueOf(id));JSONArray pageReports=new JSONArray(),groupReports=new JSONArray(),allMembers=new JSONArray();int requests=0,unknown=0;
        for(var entry:pages.entrySet()){
            List<JSONObject> groups=entry.getValue();Path source=Paths.get(groups.get(0).getString("sourcePage"));if(groups.get(0).has("sourcePageSha256")&&!hash(source).equals(groups.get(0).getString("sourcePageSha256")))throw new Exception("人工标注后源页面SHA发生变化");BufferedImage original=ImageIO.read(source.toFile());int[] sourceSize=ints(groups.get(0).getJSONArray("sourceSize"));if(original==null||original.getWidth()!=sourceSize[0]||original.getHeight()!=sourceSize[1])throw new Exception("源页面尺寸不匹配");BufferedImage current=image(original.getRGB(0,0,original.getWidth(),original.getHeight(),null,0,original.getWidth()),original.getWidth(),original.getHeight());JSONArray pageMembers=new JSONArray(),pageGroups=new JSONArray();List<JSONObject> pending=new ArrayList<>();Map<String,Map<String,JSONObject>> pageMemberMap=new LinkedHashMap<>();
            for(JSONObject group:groups){String id=group.getString("id");if(!Paths.get(group.getString("sourcePage")).equals(source))throw new Exception("Grouped source page mismatch");JSONObject active=activeGroups.get(id),report=cloneJson(group).put("apiSubmitted",false).put("apiSuccess",false).put("actualRequests",0).put("applied",false).put("status",active==null?"no_active_translations":"pending");Map<String,JSONObject> memberReports=prepareMemberReports(group,texts,active==null?Collections.emptyMap():indexed(active.getJSONArray("members")));pageMemberMap.put(id,memberReports);memberReports.values().forEach(m->{pageMembers.put(m);allMembers.put(m);});pageGroups.put(report);groupReports.put(report);
                if(active==null)continue;JSONObject request=requestMetadata(root,report);try{checkMemberTargets(active,texts);excludedMembersProtected(group,active);report.put("paragraphProtectionValidation",validateParagraphProtection(active));if(request==null||(!request.optBoolean("success")&&!request.optString("status").equals("terminal_failed")))awaitingImage(active,report,memberReports,externalQueueIds.contains(id));else applyGroup(root,original,current,active,report,texts,memberReports);}catch(Exception failure){report.put("failure",failure.toString()).put("rejectedStage",report.optString("processingStage","manifest_or_translation_validation")).put("status","failed_red");for(JSONObject m:memberReports.values())if(indexed(active.getJSONArray("members")).containsKey(m.getString("id")))m.put("failure",failure.toString()).put("groupCompositeAccepted",report.optBoolean("compositeAccepted"));pending.add(active);}for(JSONObject m:memberReports.values())if(indexed(active.getJSONArray("members")).containsKey(m.getString("id")))m.put("apiSubmitted",report.optBoolean("apiSubmitted")).put("apiSuccess",report.optBoolean("apiSuccess"));
                requests+=report.optInt("actualRequests");if(!report.optBoolean("apiSuccess")&&!report.optString("requestStatus").equals("terminal_failed"))unknown++;
            }
            for(JSONObject active:pending)redFallback(current,active,texts,pageMemberMap.get(active.getString("id")));JSONObject pageScope=verifyPageScope(original,current,groups,activeGroups);
            for(Object raw:inventory){JSONObject item=(JSONObject)raw;if(item.getInt("page")!=entry.getKey()||groupedIds.contains(item.getString("id")))continue;JSONObject member=cloneJson(item).put("apiSubmitted",false).put("apiSuccess",false).put("groupCompositeAccepted",false).put("cleanupApplied",false).put("layoutApplied",false).put("visualStatus","preserved_original_unresolved_scope").put("status","unresolved_visual_scope");pageMembers.put(member);allMembers.put(member);}
            Path dir=root.resolve("逐页").resolve(String.format("第%02d页",entry.getKey()));Files.createDirectories(dir);Files.copy(source,dir.resolve("原图.png"),StandardCopyOption.REPLACE_EXISTING);writeImage(current,dir.resolve("背景字中文回填.png"));BufferedImage marked=annotate(current,pageMembers);writeImage(marked,dir.resolve("标注_背景字传图回填区域.png"));marked.flush();compareImages(dir.resolve("原图_背景字译图对照.png"),original,current);
            Map<String,JSONObject> pageGroupReports=indexed(pageGroups);for(JSONObject group:groups){int[] sourceCrop=ints(group.getJSONArray("sourceCrop"));Path review=root.resolve("requests").resolve(group.getString("id")).resolve("回填审查");BufferedImage orig=crop(original,sourceCrop),finalRoi=crop(current,sourceCrop);writeImage(orig,review.resolve("原图ROI.png"));writeImage(finalRoi,review.resolve("实际整页回填ROI.png"));BufferedImage onlyClean=cleanupReviewPanel(orig,review.resolve("生产保护合成_仅去字.png"),pageGroupReports.get(group.getString("id")));compareImages(review.resolve("原图_去字_实际中文.png"),orig,onlyClean,finalRoi);int[] context={Math.max(0,sourceCrop[0]-50),Math.max(0,sourceCrop[1]-50),Math.min(original.getWidth(),sourceCrop[2]+50),Math.min(original.getHeight(),sourceCrop[3]+50)};BufferedImage beforeContext=crop(original,context),afterContext=crop(current,context);compareImages(review.resolve("上下文_原图_实际中文.png"),beforeContext,afterContext);orig.flush();finalRoi.flush();onlyClean.flush();beforeContext.flush();afterContext.flush();
            }
            for(Object raw:pageMembers)writeMemberArtifacts(root,original,current,(JSONObject)raw);
            JSONObject pageReport=new JSONObject().put("schemaVersion",1).put("page",entry.getKey()).put("width",original.getWidth()).put("height",original.getHeight()).put("originalFile",relative(root,dir.resolve("原图.png"))).put("translatedFile",relative(root,dir.resolve("背景字中文回填.png"))).put("annotatedFile",relative(root,dir.resolve("标注_背景字传图回填区域.png"))).put("comparisonFile",relative(root,dir.resolve("原图_背景字译图对照.png"))).put("regions",pageMembers).put("groups",pageGroups).put("counts",memberCounts(pageMembers)).put("pagePixelProtection",pageScope);save(dir.resolve("结果.json"),pageReport);pageReports.put(pageReport);System.out.println("BACKGROUND PAGE "+entry.getKey()+" "+memberCounts(pageMembers));original.flush();current.flush();
        }
        JSONObject report=new JSONObject().put("schemaVersion",1).put("pages",pageReports).put("groups",groupReports).put("regions",allMembers).put("counts",memberCounts(allMembers)).put("groupCounts",groupCounts(groupReports)).put("activeManifestGroups",activeGroups.size()).put("textTranslationsFile",manifest.getString("textTranslationsFile")).put("textTranslationsSha256",manifest.getString("textTranslationsSha256")).put("actualImageRequests",requests).put("apiGroupsUnfinished",unknown).put("allApiGroupsTerminal",unknown==0).put("allMembersVisualReview","pending").put("sourceType","manual_background_inventory_and_new_real_text_responses").put("networkCallsByRenderer",0).put("androidCanvasVerified",false).put("productionSourceSha256",hashes(project)).put("validationScope","Production ImageCleanup, RepairPixels and NearbyTextLayout methods; per-member desktop fonts; legacy bilinear resize or evidence-verified production padding recovery; group-level pixel acceptance does not prove each target's lettering was removed.");save(root.resolve("background_results.json"),report);System.out.println("BACKGROUND RENDER COMPLETE "+memberCounts(allMembers)+" "+groupCounts(groupReports));
    }
    static void controls(Path root)throws Exception{
        JSONObject inventory=json(root.resolve("background_inventory.json"));JSONArray controls=new JSONArray();Map<String,BufferedImage> pages=new HashMap<>();for(Object raw:inventory.getJSONArray("targets")){JSONObject m=cloneJson((JSONObject)raw);String path=m.getString("sourcePage");BufferedImage source=pages.get(path);if(source==null){for(BufferedImage old:pages.values())old.flush();pages.clear();source=ImageIO.read(Paths.get(path).toFile());pages.put(path,source);}writeBoundaryControl(root,source,m);controls.put(m);}for(BufferedImage old:pages.values())old.flush();save(root.resolve("目标边界控制.json"),new JSONObject().put("schemaVersion",1).put("inventorySha256",hash(root.resolve("background_inventory.json"))).put("onlyControlsNoTranslation",true).put("count",controls.length()).put("targets",controls));System.out.println("BOUNDARY CONTROLS "+controls.length());
    }
    static void validateFrozen(Path root)throws Exception{
        JSONObject manifest=json(root.resolve("cleanup_manifest.json"));Map<String,JSONObject> planned=indexed(json(root.resolve("group_plan.json")).getJSONArray("regions")),texts=indexed(frozenTranslations(root,manifest).getJSONArray("translations"));JSONArray checked=new JSONArray();Map<Path,String> sourceHashes=new HashMap<>();int members=0;
        for(Object raw:manifest.getJSONArray("regions")){JSONObject active=(JSONObject)raw,group=planned.get(active.getString("id"));if(group==null)throw new Exception("Frozen group absent from plan");checkMemberTargets(active,texts);excludedMembersProtected(group,active);JSONObject protection=validateParagraphProtection(active);ImageCleanup.prompt(active.getInt("width"),active.getInt("height"),boxes(active.getJSONArray("targetBoxes")),boxes(active.getJSONArray("protectedBoxes")));Path source=Paths.get(active.getString("sourcePage"));if(!sourceHashes.containsKey(source))sourceHashes.put(source,hash(source));if(!sourceHashes.get(source).equals(active.getString("sourcePageSha256"))||!hash(resolved(root,active.getString("inputPng"))).equals(active.getString("inputSha256")))throw new Exception("Frozen source/input hash mismatch");checked.put(protection.put("id",active.getString("id")));members+=active.getJSONArray("members").length();}
        save(root.resolve("渲染前冻结校验.json"),new JSONObject().put("valid",true).put("groups",checked).put("activeGroups",checked.length()).put("activeMembers",members).put("manifestSha256",hash(root.resolve("cleanup_manifest.json"))).put("textTranslationsFile",manifest.getString("textTranslationsFile")).put("textTranslationsSha256",manifest.getString("textTranslationsSha256")).put("networkCalls",0));System.out.println("FROZEN RENDER VALIDATION "+checked.length()+" groups / "+members+" members; zero network calls");
    }
    public static void main(String[] args)throws Exception{if(args.length>2&&args[2].equals("controls"))controls(Paths.get(args[0]));else if(args.length>2&&args[2].equals("validate"))validateFrozen(Paths.get(args[0]));else render(Paths.get(args[0]),Paths.get(args[1]));}
}
