'use strict';
const fs=require('node:fs'),path=require('node:path');
function percentile(a,p){if(!a.length)return null;const b=[...a].sort((x,y)=>x-y);return b[Math.max(0,Math.ceil(b.length*p)-1)];}
function summarize(text,expected=30,runId){const parsed=[],problems=[];for(const line of text.replace(/^\uFEFF/,'').split(/\r?\n/)){if(!line.trim())continue;try{const row=JSON.parse(line);if(row.diagnosticSchema===1)parsed.push(row);}catch{problems.push('malformed JSONL');}}
 const states=parsed.filter(r=>r.event==='capture_state');const state=runId?states.filter(r=>r.run===runId).at(-1):states.at(-1);if(!state)problems.push('missing exported capture state');const run=runId||state?.run;const rows=parsed.filter(r=>r.run===run),pages=new Map();
 if(!rows.some(r=>r.event==='capture_start'))problems.push('missing capture start (rotated or interrupted)');
 if(!state?.complete||state.dropped||state.errors||state.evicted||state.activePages)problems.push('capture incomplete, dropped, failed or still active');
 for(const row of rows)if(row.page){if(!pages.has(row.page))pages.set(row.page,{events:[],input:'',fingerprint:'',entry:row.entry});const p=pages.get(row.page);p.events.push(row);if(row.input)p.input=row.input;if(row.fingerprint)p.fingerprint=row.fingerprint;}
 const groups={},hashes=[],stats={};let closed=0;
 for(const [id,p]of pages){const begin=p.events.find(r=>r.event==='page_begin'),end=p.events.find(r=>r.event==='page_end');if(!begin||!end){problems.push('page missing begin/end '+id);continue;}closed++;if(!p.input||!p.fingerprint)problems.push('page missing stable identity '+id);if(['failed','unfinished'].includes(end.result))problems.push('failed/unfinished page '+id);const group=p.entry+'/'+end.result;groups[group]=(groups[group]||0)+1;
  const values={elapsed:end.elapsedMs,diagnostic:end.diagnosticMs},add=(k,v)=>{if(Number.isFinite(v)&&v>=0)values[k]=(values[k]||0)+v;};
  for(const e of p.events){if(e.event==='phase')add(e.stage,e.ms);if(e.event==='encode'){add('encodeCount',1);add('encodeMs',e.ms);add('encodedBytes',e.bytes);add('encode_'+e.layer+'_'+e.format,1);}if(e.event==='write')add('writtenBytes',e.bytes);if(e.event==='browser_stages')for(const k of ['load','detect','prepare','request','render','write','replace'])add('browser_'+k,e[k]);if(['pixels','file','draft'].includes(e.event))hashes.push({input:p.input,fingerprint:p.fingerprint,entry:p.entry,result:end.result,event:e.event,layer:e.layer,sha256:e.sha256});}
  const master=p.events.find(e=>e.event==='pixels'&&e.layer==='master');
  if(!master)problems.push('page missing master pixels '+id);
  const matchingLayers=new Set(['project_rendered','session_rendered','draft_rendered.png','project_draft_rendered.png','session_draft_rendered.png','export_png_readback']);
  if(master)for(const e of p.events)if(['file','pixels'].includes(e.event)&&matchingLayers.has(e.layer)&&e.sha256!==master.sha256)problems.push('master/readback mismatch '+id+'/'+e.layer);
  if(p.events.some(e=>e.event==='persistence_failure'))problems.push('persistence failure '+id);
  if(p.entry==='project'&&!p.events.some(e=>e.event==='file'&&e.layer==='project_rendered'))problems.push('project readback missing '+id);
  if(p.entry==='browser_auto'&&['new','forced','cache'].includes(end.result)&&!p.events.some(e=>e.event==='file'&&e.layer==='session_rendered'))problems.push('session readback missing '+id);
  if(end.result==='export_png'&&!p.events.some(e=>e.event==='pixels'&&e.layer==='export_png_readback'))problems.push('PNG export readback missing '+id);
  for(const[k,v]of Object.entries(values)){const key=group+'/'+k;(stats[key]||=[]).push(v);}
 }
 if(closed<expected)problems.push(`only ${closed} completed page records; expected at least ${expected}`);
 for(const[k,a]of Object.entries(stats))stats[k]={n:a.length,median:percentile(a,.5),p90:percentile(a,.9)};
 const memory=rows.filter(r=>r.event==='memory'),peak=k=>memory.length?Math.max(...memory.map(r=>r[k])):null;return {run,complete:problems.length===0,problems:[...new Set(problems)],closed,groups,stats,hashes,memory,peaks:{rss:peak('rss'),nativeBytes:peak('nativeBytes'),threads:peak('threads'),appWorkers:peak('appWorkers')},evidence:'user-exported log; not independent device acceptance; null means unmeasured'};
}
function compare(a,b){const issues=[];if(!a.complete||!b.complete)issues.push('incomplete input log');const key=r=>[r.input,r.fingerprint,r.entry,r.result,r.event,r.layer].join('|');function collect(rows){const m=new Map();for(const r of rows){const k=key(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r.sha256);}return m;}const left=collect(a.hashes),right=collect(b.hashes);for(const k of new Set([...left.keys(),...right.keys()]))if(JSON.stringify((left.get(k)||[]).sort())!==JSON.stringify((right.get(k)||[]).sort()))issues.push('missing or changed pixels/draft '+k);return {passed:issues.length===0,issues};}
if(require.main===module){const [input,out,baseline]=process.argv.slice(2);if(!input||!out){console.error('node analyze.cjs 日志.jsonl 输出目录 [另一份日志.jsonl]');process.exitCode=2;}else{const result=summarize(fs.readFileSync(input,'utf8'));fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'分析.json'),JSON.stringify(result,null,2));fs.writeFileSync(path.join(out,'内存曲线.csv'),'elapsed,nativeBytes,javaBytes,availMem,rss,threads,appWorkers\n'+result.memory.map(r=>[r.elapsed,r.nativeBytes,r.javaBytes,r.availMem,r.rss,r.threads,r.appWorkers].join(',')).join('\n'));let comparison=baseline?compare(summarize(fs.readFileSync(baseline,'utf8')),result):null;fs.writeFileSync(path.join(out,'基线报告.md'),`# 诊断日志分析\n\n状态：${result.complete?'记录完整；仍需手机功能验收':'记录不完整，不能判定通过'}\n\n完成页记录：${result.closed}\n\n问题：${result.problems.join('；')||'未检测到记录缺项'}\n\n线程峰值：${result.peaks.threads}；应用工作线程峰值：${result.peaks.appWorkers}。\n\n逐阶段中位数与 P90、编码次数、写入字节见分析.json；内存曲线见 CSV。阶段存在嵌套，不能相加当作总耗时。开启诊断的测量含哈希与回读开销，仅与同样开启诊断的版本比较。\n\n${comparison?'像素对比：'+JSON.stringify(comparison):'未提供对照日志，不作速度提升或像素一致结论。'}\n`);console.log(JSON.stringify({complete:result.complete,closed:result.closed,problems:result.problems,comparison}));if(!result.complete||comparison&&!comparison.passed)process.exitCode=1;}}
module.exports={summarize,compare,percentile};
