'use strict';
// Local deterministic fixture server. No packages, paid upstreams, or image interpretation.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),os=require('node:os');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
function args(argv){const o={port:8787,host:'0.0.0.0',images:'E:/codexwork/漫画',delay:0,rate429:0,rate503:0,scenario:'normal'};for(let i=0;i<argv.length;i+=2){const k=argv[i].replace(/^--/,'');if(!(k in o)||argv[i+1]===undefined)throw Error('Unknown/missing option '+argv[i]);o[k]=typeof o[k]==='number'?Number(argv[i+1]):argv[i+1];}if(![0,3000].includes(o.delay)||![o.rate429,o.rate503].every(x=>Number.isInteger(x)&&x>=0&&x<=100)||o.rate429+o.rate503>100||!Number.isInteger(o.port)||o.port<0||o.port>65535||!['normal','long','vertical','skip','missing','truncated','mixed'].includes(o.scenario))throw Error('Invalid options');return o;}
function texts(body){const out=[];function visit(x){if(Array.isArray(x))x.forEach(visit);else if(x&&typeof x==='object'){if(typeof x.text==='string')out.push(x.text);if(typeof x.content==='string')out.push(x.content);for(const [k,v]of Object.entries(x))if(k!=='text'&&k!=='content'||Array.isArray(v))visit(v);}}visit(body);return out;}
function translations(body,scenario){const crops=texts(body).flatMap(t=>[...t.matchAll(/裁切\s*id=([^，,\s]+)/g)].map(m=>({id:m[1],vertical:t.includes('竖排')})));const unique=[...new Map(crops.map(x=>[x.id,x])).values()];return unique.flatMap((crop,i)=>{let mode=scenario==='mixed'?['normal','long','vertical','skip','missing'][parseInt(hash(crop.id).slice(0,4),16)%5]:scenario;if(mode==='missing'&&i===unique.length-1)return [];return [{id:crop.id,originalText:mode==='skip'?'':'Synthetic fixture '+crop.id,zh:mode==='skip'?'':mode==='long'?'这是确定性的长文本排版测试，检查边界和换行。'.repeat(12):mode==='vertical'||crop.vertical?'竖排测试文字':'测试译文',skip:mode==='skip'}];});}
function imagePart(bytes,type){const b=/boundary=(?:"([^"]+)"|([^;]+))/i.exec(type);if(!b)throw Error('Missing multipart boundary');const boundary=Buffer.from('--'+(b[1]||b[2]));let at=0;while((at=bytes.indexOf(boundary,at))>=0){const header=bytes.indexOf('\r\n\r\n',at);if(header<0)break;const end=bytes.indexOf(Buffer.from('\r\n--'+(b[1]||b[2])),header+4);if(end<0)break;if(/name="image"/.test(bytes.subarray(at,header).toString('utf8')))return bytes.subarray(header+4,end);at=end+2;}throw Error('Missing image part');}
function createServer(options){const o={...args([]),...options};let requests=0;const counts=new Map();const images=fs.existsSync(o.images)?fs.readdirSync(o.images).filter(n=>/\.(png|jpe?g|webp)$/i.test(n)&&fs.statSync(path.join(o.images,n)).isFile()).sort((a,b)=>a.localeCompare(b,'en',{numeric:true})).slice(0,30):[];
 const server=http.createServer(async(req,res)=>{const send=(code,data,type='application/json; charset=utf-8')=>{res.writeHead(code,{'content-type':type,'cache-control':'no-store'});res.end(typeof data==='string'||Buffer.isBuffer(data)?data:JSON.stringify(data));};
 try{const url=new URL(req.url,'http://localhost');
 if(req.method==='GET'&&url.pathname==='/v1/models')return send(200,{object:'list',data:['mock-text','mock-image'].map(id=>({id,object:'model'}))});
 if(req.method==='GET'&&url.pathname==='/health')return send(200,{mock:true,images:images.length,delayMs:o.delay,scenario:o.scenario,rate429:o.rate429,rate503:o.rate503});
 if(req.method==='GET'&&url.pathname==='/'){const lazy=url.searchParams.get('lazy')==='1';return send(200,`<!doctype html><meta name="viewport" content="width=device-width"><title>30页翻译基准${lazy?' · 懒加载':''}</title><style>body{margin:0;background:#eee;font:18px sans-serif}header{padding:20px}img{display:block;width:min(100%,900px);height:auto;margin:16px auto}section{min-height:500px}</style><header>本地模拟基准 · ${images.length} 页 · ${o.delay} ms · ${o.scenario}<br><a href="/?lazy=0">普通版</a> | <a href="/?lazy=1">懒加载版</a><p>这是测试网页，接口只返回固定测试译文，不评估实际翻译质量。</p></header>${images.map((_,i)=>`<section><img ${lazy?'data-src':'src'}="/images/${i}" alt="基准第${i+1}页"></section>`).join('')}${lazy?`<script>const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.src=e.target.dataset.src;io.unobserve(e.target)}}),{rootMargin:'800px'});document.querySelectorAll('img').forEach(i=>io.observe(i));</script>`:''}`,'text/html; charset=utf-8');}
 if(req.method==='GET'&&/^\/images\/\d+$/.test(url.pathname)){const index=Number(url.pathname.split('/').pop());if(!Number.isSafeInteger(index)||!images[index])return send(404,{error:'image not found'});const ext=path.extname(images[index]).toLowerCase();res.writeHead(200,{'content-type':ext==='.png'?'image/png':ext==='.webp'?'image/webp':'image/jpeg','cache-control':'public, max-age=3600'});fs.createReadStream(path.join(o.images,images[index])).on('error',()=>res.destroy()).pipe(res);return;}
 if(req.method!=='POST'||!['/v1/chat/completions','/v1/responses','/v1/images/edits'].includes(url.pathname))return send(404,{error:'not found'});
 let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;if(size>24*1024*1024)return send(413,{error:'request too large'});chunks.push(chunk);}const raw=Buffer.concat(chunks);const editing=url.pathname.endsWith('/images/edits'),body=editing?null:JSON.parse(raw.toString('utf8'));const crop=editing?imagePart(raw,req.headers['content-type']||''):null;const identity=hash(editing?crop:JSON.stringify(body)).slice(0,16);const occurrence=(counts.get(identity)||0)+1;counts.set(identity,occurrence);if(counts.size>10000)counts.delete(counts.keys().next().value);requests++;const slot=(requests-1)%100;const status=slot<o.rate429?429:slot<o.rate429+o.rate503?503:200;
 console.log(JSON.stringify({request:requests,route:url.pathname,identity,occurrence,bytes:size,status,delayMs:o.delay}));
 if(o.delay)await new Promise(resolve=>setTimeout(resolve,o.delay));if(res.destroyed)return;
 if(status!==200){res.setHeader('retry-after','1');return send(status,{error:{message:'Synthetic '+status,type:'mock_injected'}});}
 if(editing)return send(200,{created:0,data:[{b64_json:crop.toString('base64')}]});
 let content=JSON.stringify({translations:translations(body,o.scenario)}),truncated=o.scenario==='truncated';if(truncated)content=content.slice(0,Math.max(1,content.length-15));
 if(url.pathname.endsWith('/responses'))return send(200,{id:'mock-'+identity,object:'response',status:truncated?'incomplete':'completed',incomplete_details:truncated?{reason:'max_output_tokens'}:null,output:[{type:'message',role:'assistant',content:[{type:'output_text',text:content}]}],usage:{input_tokens:0,output_tokens:0,total_tokens:0}});
 return send(200,{id:'mock-'+identity,object:'chat.completion',choices:[{index:0,message:{role:'assistant',content},finish_reason:truncated?'length':'stop'}],usage:{prompt_tokens:0,completion_tokens:0,total_tokens:0}});
 }catch(error){if(!res.headersSent)send(400,{error:{message:'Invalid mock request'}});else res.destroy();}
 });return server;}
if(require.main===module){const o=args(process.argv.slice(2)),server=createServer(o);server.listen(o.port,o.host,()=>{console.log('本地测试服务器：无上游请求，不花费 API 额度。只服务指定目录最多30张图片。');for(const list of Object.values(os.networkInterfaces()))for(const nic of list||[])if(nic.family==='IPv4'&&!nic.internal)console.log(`API http://${nic.address}:${server.address().port}/v1  网页 http://${nic.address}:${server.address().port}/`);console.log(JSON.stringify({delayMs:o.delay,scenario:o.scenario,images:o.images}));});}
module.exports={args,translations,imagePart,createServer};
